<a href="https://colab.research.google.com/github/gracesjy/mldl_study/blob/main/03_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **인피니티북스 "누구나 쉽게 배우는 딥러닝 스타트"(1판) 교재 소스 코드**

## **3장 개발환경구축과 넘파이**
---
* 출판사 : 인피니티북스( https://www.infinitybooks.co.kr )
* 저자 : 박동규
* 소스코드 저장소 : https://github.com/dongupak/DLstart
* 저작권 : 본 주피터 노트북 코드는 자유롭게 배포가능하지만 위의 출판사, 저자 표기와 함께 배포해 주십시오.
 * https://www.yes24.com/Product/Goods/124152667
 * 책의 오류는 dongupak@gmail.com 으로 알려주십시오.
---

### 3.1 파이썬과 구글 코랩
#### 파이썬 프로그래밍 언어

In [ ]:
animals = ['lion', 'tiger', 'cat', 'dog']
animals.sort()            # animals 리스트 내부 문자열을 알파벳 순으로 정렬
animals

['cat', 'dog', 'lion', 'tiger']

In [ ]:
animals.append('rabbit')  # animals 리스트에 새 원소를 추가
animals

['cat', 'dog', 'lion', 'tiger', 'rabbit']

In [ ]:
animals.reverse()
animals

['rabbit', 'tiger', 'lion', 'dog', 'cat']

#### 코랩 환경에서 코딩하기

In [ ]:
print('Hello Python')

Hello Python


In [ ]:
print('Welcome to Deep Learning!')

Welcome to Deep Learning!


---
### 3.2 구글 코랩의 여러가지 기능들

---

In [ ]:
import tensorflow as tf    # tensorflow의 별명은 tf로 한다

print(tf.__version__)      # version 앞뒤로 두 개의 밑줄을 사용한다

2.15.0


### 3.3 강력한 기능을 가진 넘파이를 알아보자

In [ ]:
import numpy as np   # numpy의 별칭으로 np를 지정함

a = np.array([2, 3, 4])  # 다차원 배열 객체

In [ ]:
a = np.array([2, 3, 4])       # 넘파이 ndarray 객체의 생성

# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])  # 넘파이 ndarray 객체의 b 생성
b.shape

(2, 3)

#### 파이썬의 강력한 자료구조인 리스트와 넘파이의 다차원 배열

In [ ]:
mid_score_lst = [70, 85, 92, 79]
# 파이썬의 리스트를 이용하여 성적을 저장
print('중간 시험 점수들 :', mid_score_lst)

중간 시험 점수들 : [70, 85, 92, 79]


In [ ]:
student_mid = [70, 85, 92, 79] # 중간시험 성적
student_fin = [90, 65, 70, 85] # 기말시험 성적
student_sum = student_mid + student_fin
print('중간시험과 기말시험 성적의 합 :', student_sum)

중간시험과 기말시험 성적의 합 : [70, 85, 92, 79, 90, 65, 70, 85]


In [ ]:
student_sum / 2   # 오류! : 리스트는 나누기 연산을 지원하지 않음

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
student_mid = np.array([70, 85, 92, 79]) # 중간시험 성적
student_fin = np.array([90, 65, 70, 85]) # 기말시험 성적
student_sum = student_mid + student_fin
print('중간시험과 기말시험 성적의 합 :', student_sum)

중간시험과 기말시험 성적의 합 : [160 150 162 164]


In [ ]:
print('평균 성적 :', student_sum/2)

평균 성적 : [80. 75. 81. 82.]


#### 다차원 배열의 연산

In [ ]:
a = np.array([10, 20, 30])    # 넘파이 ndarray 객체 a 생성
b = np.array([1, 2, 3])       # 넘파이 ndarray 객체 b 생성
a + b

array([11, 22, 33])

In [ ]:
a - b

array([ 9, 18, 27])

In [ ]:
a * b

array([10, 40, 90])

In [ ]:
a / b

array([10., 10., 10.])

----
#### 편리하고 강력한 브로드캐스팅과 벡터화 연산

In [ ]:
a = np.array([10, 20, 30])
a * 10

array([100, 200, 300])

In [ ]:
a + 10

array([20, 30, 40])

In [ ]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4])
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [ ]:
b * c

array([[ 20,  60, 120],
       [ 80, 150, 240]])

#### 다차원 배열을 쉽게 생성해 보자


In [ ]:
import numpy as np

np.array(range(1, 11))     # 파이썬의 range() 함수로 연속된 수를 만든다

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.zeros((2, 3))     # 2행 3열의 행렬 생성 시 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))      # 2행 3열의 행렬 생성 시 모든 값을 1로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2, 3), 100) # 2행 3열의 행렬 생성 시 모든 값을 100으로

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(3)            # 3x3 크기의 단위행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
#### 다차원 배열을 합하는 append() 함수

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append([a], b, axis = 0)     # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.array([[1, 2], [3, 4]])     # 2차원 배열 a
b = np.array([[10, 20], [30, 40]]) # 2차원 배열 b
a * b         # 2차원 배열의 곱하기 연산 - 원소 간의 곱셈

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
np.matmul(a, b)     # 2차원 배열 a, b의 행렬곱, a @ b와 같다

array([[ 70, 100],
       [150, 220]])

In [ ]:
a @ b               # 2차원 배열 a, b의 행렬곱, 위의 결과와 동일함

array([[ 70, 100],
       [150, 220]])

---
### 3.4 넘파이의 고급 기능을 알아보자

#### 인덱싱과 슬라이싱

In [ ]:
import numpy as np

arr_2d = np.array( [[1, 2, 3], [4, 5, 6],
                    [7, 8, 9], [0, 1, 2]] )

In [ ]:
# 첫 번째 행의 첫 번째 데이터
print(arr_2d[0][0])
# 세 번째 열의 데이터
print(arr_2d[2])

1
[7 8 9]


In [ ]:
arr_2d[1:][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
length0, length1 = arr_2d.shape
for i in range(length0):
   for j in range(length1):
       print(arr_2d[i][j], arr_2d[i, j]) # 두 방식의 결과는 동일함

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


In [ ]:
ages = np.array([28, 25, 12, 16, 20])

In [ ]:
y = ages >= 21
y

array([ True,  True, False, False, False])

In [ ]:
age_over_21 = ages[ ages>= 21 ]
print(f'age_over_21 = {age_over_21}')

age_over_21 = [28 25]


#### 난수를 생성해보자

In [ ]:
import numpy as np
rnd = np.random.randn(5) * 10 + 165 # 평균값이 165,표준편차가 10인 값 생성
rnd

array([162.18292527, 158.58215035, 161.01449835, 167.8355536 ,
       170.10304917])

In [ ]:
rnd.round(2)     # 소수점 아래 둘째 자리까지 값으로 변환

array([162.18, 158.58, 161.01, 167.84, 170.1 ])

In [ ]:
rnd.astype(int)     # 정수형 자료형으로 변환

array([162, 158, 161, 167, 170])

In [ ]:
np.random.seed(42)  # 씨드값이 특정되면 매번 동일한 난수의 열이 생성됨

In [ ]:
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2)
nums

array([[169.97, 163.62, 171.48, 180.23],
       [162.66, 162.66, 180.79, 172.67],
       [160.31, 170.43, 160.37, 160.34]])

In [ ]:
a = np.arange(10)  # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 값을 생성
np.random.shuffle(a)
a                  # a에는 순서가 뒤섞인 값이 들어있다

array([1, 7, 6, 2, 8, 0, 3, 4, 5, 9])

In [ ]:
# permutation() 함수는 리스트 원소를 랜덤한 순서로 재배치한 후
# ndarray로 반환한다.
np.random.permutation([2, 4, 6, 8, 10])

array([ 2,  4, 10,  8,  6])

In [ ]:
a = np.arange(10)  # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 값을 생성
np.random.shuffle(a)
print('50% 데이터 :', a[:5])        # 순서가 뒤섞인 값이 5개 들어있다
print('나머지 50% 데이터 :', a[5:])  # 순서가 뒤섞인 값이 5개 들어있다

50% 데이터 : [5 3 1 6 0]
나머지 50% 데이터 : [7 9 4 2 8]


---
#### 여러 개의 배열값을 얻는 방법

In [ ]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.logspace(0, 5, 10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

#### 배열의 형태를 바꾸는 reshape() 메소드와 flatten() 메소드

In [ ]:
import numpy as np

y = np.arange(12)   # 0에서 11까지 12개의 수를 생성한다
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
y.reshape(3, 4)     # 다차원 배열의 shape을 (3, 4)로 만든다

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y.reshape(-1, 4)     # 다차원 배열의 shape을 (3, 4)로 만든다

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 차원을 3차원으로 만든다, [[[로 시작 ]]]로 마침
y.reshape(-1, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# 3차원 배열을 만든다
y.reshape(-1, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
y = np.arange(3)     # 1차원 배열
y = y[:, np.newaxis] # 차원을 2차원으로 만든다
y

array([[0],
       [1],
       [2]])

In [ ]:
y = np.arange(3)
y = y[:, np.newaxis, np.newaxis]# 차원을 3차원으로 만든다
y

array([[[0]],

       [[1]],

       [[2]]])

In [ ]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.flatten()    # 넘파이 다차원 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

In [ ]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.T

array([[1, 2, 3],
       [1, 2, 3]])

### 3.5 딥러닝을 위한 행렬
#### 딥러닝을 위한 행렬의 핵심 개념


In [ ]:
import numpy as np

a = np.array([1, -4])
b = np.array([3, 6])
print('a =', a)
print('b =', b)

a = [ 1 -4]
b = [3 6]


In [ ]:
print('a dot b = ', np.dot(a, b))

a dot b =  -21


In [ ]:
print('a dot b = ', a.dot(b))

a dot b =  -21


In [ ]:
u = np.array([1, 2, 0, -1])
v = np.array([2, 2, 3, 4])
print('u dot v = ', np.dot(u, v))

u dot v =  2


In [ ]:
print('u * v =', u * v)

u * v = [ 2  4  0 -4]


In [ ]:
print('np.sum(u * v) =', np.sum(u * v))

np.sum(u * v) = 2


#### 행렬 곱 연산

In [ ]:
a = np.array([[1, 2], [3, 4]])     # 2차원 배열 a
b = np.array([[10, 20], [30, 40]]) # 2차원 배열 b
a * b    # 행렬간의 원소 곱 연산자 *를 사용해 보자

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
a = np.array([[1, 2], [3, 4]])     # 2차원 배열 a
b = np.array([[10, 20], [30, 40]]) # 2차원 배열 b
np.matmul(a, b)

array([[ 70, 100],
       [150, 220]])

In [ ]:
a @ b

array([[ 70, 100],
       [150, 220]])

In [ ]:
X = [2, 3]
W = [[1, 2, 1], [2, 5, 1]]  # W는 (2, 3)크기의 행렬
np.matmul(X, W)       # X행렬과 W의 곱의 결과

array([ 8, 19,  5])

### 단위 행렬과의 곱

In [ ]:
a = [[1, 2], [3, 4]]
b = [[1, 0], [0, 1]]  # b는 단위행렬
np.matmul(a, b)       # a행렬과 단위행렬 b의 곱의 결과

array([[1, 2],
       [3, 4]])

In [ ]:
c = [[1, 2, -1], [3, 4, 5], [2, 1, 0]]
d = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]  # d는 (3, 3)크기의 단위행렬
np.matmul(c, d)       # c행렬과 단위행렬 d의 곱의 결과

array([[ 1,  2, -1],
       [ 3,  4,  5],
       [ 2,  1,  0]])